name: Node.js CI/CD on Amazon Linux

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: REMOTE_HOST

    steps:
    # 1️⃣ Checkout the repository
    - uses: actions/checkout@v2

    # 2️⃣ Install dependencies
    - name: Install dependencies
      run: npm install

    # 3️⃣ Build the NestJS project
    - name: Build NestJS project
      run: npm run build

    # 4️⃣ Optional: list files for debugging
    - name: List files after build
      run: ls -R

    # 5️⃣ Test SSH key secret
    - name: Test SSH key secret
      run: |
        if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "SSH_PRIVATE_KEY is empty!"
          exit 1
        else
          echo "SSH_PRIVATE_KEY is present ✅"
        fi

    # 6️⃣ Deploy compiled files
    - name: Deploy compiled files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: dist,package.json,package-lock.json
        target: "/var/www/ovis-backend"

    # 7️⃣ Install production dependencies & restart PM2
    - name: Restart PM2 application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/ovis-backend
          npm install --production
          pm2 start dist/main.js --name ovis-backend || pm2 reload ovis-backend
